apiVersion: v1
kind: ConfigMap
metadata:
  name: snow-config
data:
  spring.application.name: "Snowflake ID Generator"
  snowflake-settings.starting-epoch: "946684800"
  snowflake-settings.datacenter-id: "1"
