apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubectl describe svc snow-service
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  rules:
    - host: snowflake.dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snow-service
                port:
                  number: 80


